### ISSUE TITLE
UndefVarError: Advection not defined

### ISSUE THREAD

**Issue by gregbritten** [gregbritten/TurbulentBlooms.jl#6]
Updated to most recent Oceananigans.jl

Tried to run critical_turbulence_hypothesis.jl and got an error loading the packages

Only `Oceananigans.Advection` fails, giving the error above

**Comment by glwagner** [comment]
I bet the update didn't work as expected. Print the result of

```
julia --project -e 'using Pkg; Pkg.status()'
```

**Comment by gregbritten** [comment]
Got it working! Updated Julia to 1.5 and re-installed Oceananigans 
..now my phytoplankton simulation isn't returning NaNs.. it's just not moving from the initial condition and I don't know why - will investigate further!
