### ISSUE TITLE
Change mu function to be decreasing function of depth

### ISSUE THREAD

**Issue by gregbritten** [gregbritten/TurbulentBlooms.jl#8]
https://github.com/gregbritten/TubulentBlooms.jl/blob/master/critical_turbulence_hypothesis.jl#L81

Should be `@inline μ(z, μ₀, h) = μ₀ * exp(-z / h)`
instead of 
`@inline μ(z, μ₀, h) = μ₀ * exp(z / h)`

**Comment by gregbritten** [comment]
The simulation doesn't NaN out, but still doesn't look right...
?? Does oceananigans define `z` as negative ??

**Comment by glwagner** [comment]
z increases _upwards_ (like z should --- remember we do things _logically_, which is not necessarily standard in oceanography). 

z is 0 at the surface, and decreases toward the bottom where it's equal to -Lz.

**Comment by gregbritten** [comment]
right.. *logically*, need to remember that..
